### ISSUE TITLE
Misspelling 'files' causes segfault

### ISSUE THREAD

**Issue by drGrove** [viaduct-ai/kustomize-sops#58]
## Stacktrace
```
→ kustomize build --enable_alpha_plugins .  
2020/09/03 19:13:36 Attempting plugin load from '/home/user/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x7f9f3b58ab49]

goroutine 1 [running]:
github.com/viaduct-ai/kustomize-sops.UpdateResourceOptions(0x0, 0x0, 0x0, 0x0, 0xc000120840, 0xc000d1f930)
        /home/user/.go/src/github.com/viaduct-ai/kustomize-sops/ksops.go:84 +0x39
github.com/viaduct-ai/kustomize-sops.(*plugin).Generate(0xc0009ddc20, 0xc0007856f0, 0x1, 0x1, 0xc0007856e0)
        /home/user/.go/src/github.com/viaduct-ai/kustomize-sops/ksops.go:77 +0xfd
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).runGenerators(0xc00003c9c0, 0xc000354f40, 0xc0001928c0, 0x0)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/api@v0.6.0/internal/target/kusttarget.go:223 +0x1b3
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).accumulateTarget(0xc00003c9c0, 0xc000354f40, 0x0, 0x4, 0x1)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/api@v0.6.0/internal/target/kusttarget.go:189 +0x255
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).AccumulateTarget(0xc00003c9c0, 0x40, 0x0, 0x1)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/api@v0.6.0/internal/target/kusttarget.go:154 +0xc6
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc00003c9c0, 0x0, 0x0, 0x249eaa0, 0x32e3258)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/api@v0.6.0/internal/target/kusttarget.go:109 +0x2f
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/api@v0.6.0/internal/target/kusttarget.go:105
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc000d1fd18, 0x7ffd3739816d, 0x1, 0x0, 0x0, 0x0, 0x0)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/api@v0.6.0/krusty/kustomizer.go:77 +0x28d
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc000123a40, 0x2435340, 0xc000120008, 0x2, 0x0)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.8.2/internal/commands/build/build.go:143 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc00020f080, 0xc000395560, 0x1, 0x2, 0x0, 0x0)
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.8.2/internal/commands/build/build.go:70 +0xab
github.com/spf13/cobra.(*Command).execute(0xc00020f080, 0xc000395540, 0x2, 0x2, 0xc00020f080, 0xc000395540)
        /home/user/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00020eb00, 0x9, 0x2489740, 0xc000465220)
        /home/user/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /home/user/.go/pkg/mod/sigs.k8s.io/kustomize/kustomize/v3@v3.8.2/main.go:23 +0x71
```

### Invalid File in question

```
# secret-generator.yaml
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: ksops-secrets
file: # This should be "files"
  - certificate.enc.yaml
```

**Comment by devstein** [comment]
@drGrove Thanks for making an issue! Not sure how this has gone unnoticed for so long 😅
